name: Code Quality
on:
    workflow_call:

jobs:
    code-quality:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout 
              uses: actions/checkout@v4

            - name: setup python
              uses: actions/setup-python@v4
              with:
                python-version: '3.14'
                cache: pip

            - name: install dependencies
              run: pip install -r requirements.txt

            - name: run linter
              run: flake8 app.py

            - name: run SAST
              run: bandit -r app.py


