name: Dependency scan
on:
    workflow_call:

jobs:
    dependency-check:
        runs-on: ubuntu-latest
        steps:
            - name: Code Checkout
              uses: actions/checkout@v6

            - name: setup python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: Install Pip audit
              run: pip install pip-audit
             

            - name: Audit dependencies
              run: pip-audit -r requirements.txt
