name: Deploy to Server
on:
    workflow_call:


jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            DOCKERHUB_USER: ${{ vars.DOCKERHUB_USER }}
            DOCKER_TAG: ${{ github.sha }}
        steps:
            - name: Code Checkout
              uses: actions/checkout@v6

            - name: SSH to Prod Server
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                script: |
                  echo "Starting Deployment"
                  mkdir -p devops
                  echo "Installing Prerequisites"
                  sudo apt-get update -y && sudo apt install docker.io docker-compose-v2 -y
                  sudo usermod -aG docker $USER && newgrp docker

              
            - name: Copy docker compose to server
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                source: "*"
                target: ~/devops

            - name: SSH to Prod Server
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                script: |
                  export DOCKERHUB_USER=${{ vars.DOCKERHUB_USERNAME }}
                  export DOCKER_TAG=${{ github.sha }}
                  echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ vars.DOCKERHUB_USERNAME }} --password-stdin
                  cd ~/devops && docker compose down && docker compose up -d --build --force-recreate --pull always



                

