name: Deploy to Server
on:
    workflow_call:


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: SSH to Prod Server
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.PRIVATE_KEY }}
                script: |
                  echo "Starting Deployment"
                  mkdir devops
                

