name: Devsecops Pipeline

on:
    workflow_dispatch:

jobs:
    code-quality:
      uses: ./.github/workflows/code-quality.yml
                
    secrets-scan:
        uses: ./.github/workflows/secrets-scan.yml

    dependency-scan:
        uses: ./.github/workflows/dependancy-scan.yml

    docker-scan:
        uses: ./.github/workflows/docker-lint.yml

    build:
        needs: [code-quality, secrets-scan, dependency-scan, docker-scan]
        uses: ./.github/workflows/build-and-push.yml
        secrets: inherit
    
    trivy:
        needs: [build]
        uses: ./.github/workflows/image-scan.yml
        secrets: inherit
        