name: docker lint
on:
    workflow_call:

jobs:
    validate-dockerfile:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v6

            - name: Validate Docker file
              uses: hadolint/hadolint-action@v3.1.0
              with:
                dockerfile: Dockerfile
                